### ISSUE TITLE
PokerStarsParser doesn't work

### ISSUE THREAD

**Issue by xrchz** [uoftcprg/pokerkit#38]
I have been trying to parse a hand history download from PokerStars using pokerkit without much success. It looks like the format expected by the regexes in the pokerkit code don't actually match very well with what PokerStars format looks like. Do you have or need some examples to test against?

**Comment by AussieSeaweed** [comment]
Hi.

This is kind of a known issue. The [PokerStars hand histories I worked with](https://github.com/uoftcprg/phh-dataset) are from 2009. The parsers are a bit fragile, and I think PokerStars formats changed a bit since then. If you can send me some of the histories you are working with, I can take a look.

**Comment by AussieSeaweed** [comment]
Fixed in f2313940e4ece716a721720a6b785218a86f4ac6

**Comment by xrchz** [comment]
So the change above does allow hands to be found in a hand history, but the hands themselves still fail to parse. Can you please verify that the parser works on the example I provided?

(@AussieSeaweed I can't reopen the issue, but I think it's not done.)

**Comment by AussieSeaweed** [comment]
It seems to work on my end.

```python
from pokerkit import *

text = '''
Hand #112181:

PokerStars Zoom Hand #259026696773:  Hold'em No Limit ($0.02/$0.05) - 2025/12/24 18:13:43 ET
Table 'Donati' 6-max Seat #1 is the button
Seat 1: AJIykapD1992 ($1.22 in chips)
Seat 2: octavian1971 ($12.16 in chips)
Seat 3: Apacman619 ($5 in chips)
Seat 4: JackPotTheG420 ($5.73 in chips)
Seat 5: loyan29 ($7.07 in chips)
Seat 6: xrchz ($6.21 in chips)
octavian1971: posts small blind $0.02
Apacman619: posts big blind $0.05
*** HOLE CARDS ***
Dealt to xrchz [8c 6c]
JackPotTheG420: folds
loyan29: folds
xrchz: folds
AJIykapD1992: raises $0.05 to $0.10
octavian1971: calls $0.08
Apacman619: calls $0.05
*** FLOP *** [2s 2h 9d]
octavian1971: checks
Apacman619: checks
AJIykapD1992: checks
*** TURN *** [2s 2h 9d] [9s]
octavian1971: checks
Apacman619: checks
AJIykapD1992: checks
*** RIVER *** [2s 2h 9d 9s] [Js]
octavian1971: bets $0.45
Apacman619: folds
AJIykapD1992: folds
Uncalled bet ($0.45) returned to octavian1971
octavian1971 collected $0.29 from pot
octavian1971: doesn't show hand
*** SUMMARY ***
Total pot $0.30 | Rake $0.01
Board [2s 2h 9d 9s Js]
Seat 1: AJIykapD1992 (button) folded on the River
Seat 2: octavian1971 (small blind) collected ($0.29)
Seat 3: Apacman619 (big blind) folded on the River
Seat 4: JackPotTheG420 folded before Flop (didn't bet)
Seat 5: loyan29 folded before Flop (didn't bet)
Seat 6: xrchz folded before Flop (didn't bet)

Hand #112182:

PokerStars Zoom Hand #259026698392:  Hold'em No Limit ($0.02/$0.05) - 2025/12/24 18:13:53 ET
Table 'Donati' 6-max Seat #1 is the button
Seat 1: epix23 ($6.62 in chips)
Seat 2: theblefe171 ($7.54 in chips)
Seat 3: oracioliveir ($2.59 in chips)
Seat 4: ciceron86 ($5.02 in chips)
Seat 5: xrchz ($6.21 in chips)
Seat 6: AdamLongDong ($1.85 in chips)
theblefe171: posts small blind $0.02
oracioliveir: posts big blind $0.05
*** HOLE CARDS ***
Dealt to xrchz [6c Kh]
ciceron86: folds
xrchz: folds
AdamLongDong: folds
epix23: raises $0.07 to $0.12
theblefe171: folds
oracioliveir: calls $0.07
*** FLOP *** [Qh 3c Td]
oracioliveir: bets $0.13
epix23: calls $0.13
*** TURN *** [Qh 3c Td] [7s]
oracioliveir: checks
epix23: bets $0.38
oracioliveir: calls $0.38
*** RIVER *** [Qh 3c Td 7s] [9s]
oracioliveir: checks
epix23: checks
*** SHOW DOWN ***
oracioliveir: shows [Tc Ks] (a pair of Tens)
epix23: mucks hand
oracioliveir collected $1.23 from pot
*** SUMMARY ***
Total pot $1.28 | Rake $0.05
Board [Qh 3c Td 7s 9s]
Seat 1: epix23 (button) mucked [Kc Ad]
Seat 2: theblefe171 (small blind) folded before Flop
Seat 3: oracioliveir (big blind) showed [Tc Ks] and won ($1.23) with a pair of Tens
Seat 4: ciceron86 folded before Flop (didn't bet)
Seat 5: xrchz folded before Flop (didn't bet)
Seat 6: AdamLongDong folded before Flop (didn't bet)
'''

hhs = list(HandHistory.from_pokerstars(text))

print(HandHistory.dumps_all(hhs))
```

The output is

```console
[1]
variant = 'NT'
ante_trimming_status = false
antes = [0, 0, 0, 0, 0, 0]
blinds_or_straddles = [0.02, 0.05, 0, 0, 0, 0]
min_bet = 0.05
starting_stacks = [12.16, 5, 5.73, 7.07, 6.21, 1.22]
actions = ['d dh p1 ????', 'd dh p2 ????', 'd dh p3 ????', 'd dh p4 ????', 'd dh p5 8c6c', 'd dh p6 ????', 'p3 f', 'p4 f', 'p5 f', 'p6 cbr 0.10', 'p1 cc', 'p2 cc', 'd db 2s2h9d', 'p1 cc', 'p2 cc', 'p6 cc', 'd db 9s', 'p1 cc', 'p2 cc', 'p6 cc', 'd db Js', 'p1 cbr 0.45', 'p2 f', 'p6 f']
venue = 'PokerStars'
time = 18:13:43
day = 24
month = 12
year = 2025
seats = [2, 3, 4, 5, 6, 1]
seat_count = 6
table = 'Donati'
players = ['octavian1971', 'Apacman619', 'JackPotTheG420', 'loyan29', 'xrchz', 'AJIykapD1992']
winnings = [0, 0, 0, 0, 0, 0]
currency_symbol = '$'
time_zone_abbreviation = 'ET'

[2]
variant = 'NT'
ante_trimming_status = false
antes = [0, 0, 0, 0, 0, 0]
blinds_or_straddles = [0.02, 0.05, 0, 0, 0, 0]
min_bet = 0.05
starting_stacks = [7.54, 2.59, 5.02, 6.21, 1.85, 6.62]
actions = ['d dh p1 ????', 'd dh p2 ????', 'd dh p3 ????', 'd dh p4 6cKh', 'd dh p5 ????', 'd dh p6 ????', 'p3 f', 'p4 f', 'p5 f', 'p6 cbr 0.12', 'p1 f', 'p2 cc', 'd db Qh3cTd', 'p2 cbr 0.13', 'p6 cc', 'd db 7s', 'p2 cc', 'p6 cbr 0.38', 'p2 cc', 'd db 9s', 'p2 cc', 'p6 cc', 'p2 sm TcKs', 'p6 sm ????']
venue = 'PokerStars'
time = 18:13:53
day = 24
month = 12
year = 2025
seats = [2, 3, 4, 5, 6, 1]
seat_count = 6
table = 'Donati'
players = ['theblefe171', 'oracioliveir', 'ciceron86', 'xrchz', 'AdamLongDong', 'epix23']
currency_symbol = '$'
time_zone_abbreviation = 'ET'
```

**Comment by xrchz** [comment]
Can you test these hands too?

```
﻿
Hand #1: 

PokerStars Hand #218222819469: Tournament #3000337141, $0.44+$0.06 USD Hold'em No Limit - Level I (10/20) - 2020/09/07 17:25:37 ET
Table '3000337141 1' 9-max Seat #1 is the button
Seat 1: Kanrk (1500 in chips) 
Seat 2: mzillinho (1500 in chips) 
Seat 3: leslavigueurs (1500 in chips) 
Seat 4: said809 (1500 in chips) 
Seat 5: Richard_KONO (1500 in chips) 
Seat 6: mun rá38 (1500 in chips) 
Seat 7: DOORY_72 (1500 in chips) 
Seat 8: xrchz (1500 in chips) 
Seat 9: VovaPunisher (1500 in chips) 
mzillinho: posts small blind 10
leslavigueurs: posts big blind 20
*** HOLE CARDS ***
Dealt to xrchz [4c Qc]
said809 is disconnected 
Kanrk is disconnected 
said809 is connected 
leslavigueurs is disconnected 
said809: folds 
Richard_KONO: folds 
mun rá38: folds 
DOORY_72: folds 
xrchz: folds 
VovaPunisher: folds 
Kanrk: calls 20
mzillinho: calls 10
leslavigueurs: checks 
*** FLOP *** [7c 6h 4s]
mzillinho: checks 
leslavigueurs: checks 
Kanrk: bets 100
mzillinho: calls 100
leslavigueurs: folds 
*** TURN *** [7c 6h 4s] [9h]
mzillinho: checks 
Kanrk: bets 100
mzillinho: calls 100
*** RIVER *** [7c 6h 4s 9h] [8h]
mzillinho: checks 
Kanrk: bets 20
mzillinho: calls 20
*** SHOW DOWN ***
Kanrk: shows [7h 7d] (three of a kind, Sevens)
mzillinho: mucks hand 
Kanrk collected 500 from pot
*** SUMMARY ***
Total pot 500 | Rake 0 
Board [7c 6h 4s 9h 8h]
Seat 1: Kanrk (button) showed [7h 7d] and won (500) with three of a kind, Sevens
Seat 2: mzillinho (small blind) mucked [3s Qd]
Seat 3: leslavigueurs (big blind) folded on the Flop
Seat 4: said809 folded before Flop (didn't bet)
Seat 5: Richard_KONO folded before Flop (didn't bet)
Seat 6: mun rá38 folded before Flop (didn't bet)
Seat 7: DOORY_72 folded before Flop (didn't bet)
Seat 8: xrchz folded before Flop (didn't bet)
Seat 9: VovaPunisher folded before Flop (didn't bet)

Hand #2: 

PokerStars Hand #218222860558: Tournament #3000337141, $0.44+$0.06 USD Hold'em No Limit - Level I (10/20) - 2020/09/07 17:26:40 ET
Table '3000337141 1' 9-max Seat #2 is the button
Seat 1: Kanrk (1760 in chips) 
Seat 2: mzillinho (1260 in chips) 
Seat 3: leslavigueurs (1480 in chips) 
Seat 4: said809 (1500 in chips) 
Seat 5: Richard_KONO (1500 in chips) 
Seat 6: mun rá38 (1500 in chips) 
Seat 7: DOORY_72 (1500 in chips) 
Seat 8: xrchz (1500 in chips) 
Seat 9: VovaPunisher (1500 in chips) 
leslavigueurs: posts small blind 10
said809: posts big blind 20
*** HOLE CARDS ***
Dealt to xrchz [Kc As]
Richard_KONO: folds 
mun rá38: calls 20
DOORY_72: folds 
xrchz: raises 40 to 60
VovaPunisher: folds 
Kanrk: folds 
mzillinho: folds 
leslavigueurs: folds 
said809: folds 
mun rá38: calls 40
*** FLOP *** [Kh 9h 6c]
mun rá38: bets 20
xrchz: raises 95 to 115
mun rá38: calls 95
*** TURN *** [Kh 9h 6c] [5h]
mun rá38: bets 20
xrchz: raises 210 to 230
mun rá38: raises 1095 to 1325 and is all-in
xrchz: calls 1095 and is all-in
*** RIVER *** [Kh 9h 6c 5h] [6d]
*** SHOW DOWN ***
mun rá38: shows [Qh 7h] (a flush, King high)
xrchz: shows [Kc As] (two pair, Kings and Sixes)
mun rá38 collected 3030 from pot
xrchz finished the tournament in 9th place
*** SUMMARY ***
Total pot 3030 | Rake 0 
Board [Kh 9h 6c 5h 6d]
Seat 1: Kanrk folded before Flop (didn't bet)
Seat 2: mzillinho (button) folded before Flop (didn't bet)
Seat 3: leslavigueurs (small blind) folded before Flop
Seat 4: said809 (big blind) folded before Flop
Seat 5: Richard_KONO folded before Flop (didn't bet)
Seat 6: mun rá38 showed [Qh 7h] and won (3030) with a flush, King high
Seat 7: DOORY_72 folded before Flop (didn't bet)
Seat 8: xrchz showed [Kc As] and lost with two pair, Kings and Sixes
Seat 9: VovaPunisher folded before Flop (didn't bet)
```

**Comment by AussieSeaweed** [comment]
The tournament logs can now be parsed as of 9d2646497bf2a9355d5eb4c17d4dbe47740809cc. It is also available in Version 0.7.2.
